application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk Maya 2016x64"
arguments = [ "-proj", "{MINDBENDER_WORKDIR}",]
schema = "mindbender-core:application-1.0"
executable = "maya2016"
description = ""

[copy]
"{MINDBENDER_CORE}/res/workspace.mel" = "workspace.mel"

[environment]
MAYA_DISABLE_CLIC_IPM = "Yes"  # Disable the AdSSO process
MAYA_DISABLE_CIP = "Yes"  # Shorten time to boot
MAYA_DISABLE_CER = "Yes"
PYTHONPATH = [
	"{MINDBENDER_CORE}/setup/maya",
	"{PYTHONPATH}"
]
